/*editor*/
export const SET_EDITOR = "SET_EDITOR"
export const NEW_EDITOR = "NEW_EDITOR"
export const UNDO = "UNDO"
export const REDO = "REDO"

/*elements*/
    /*main*/
export const CHOOSE_ELEMENTS = "CHOOSE_ELEMENTS"
export const ADD_ELEMENT = "ADD_ELEMENT"
export const DELETE_ELEMENTS = "DELETE_ELEMENTS"
export const PASTE_ELEMENT = "PASTE_ELEMENT"
    /*move*/
export const END_MOVE_ELEMENTS = "END_MOVE_ELEMENTS"
export const CHANGE_POSITION_OF_ELEMENTS = "CHANGE_POSITION_OF_ELEMENTS"
    /*styles*/
export const CHANGE_ELEMENT_FILL_COLOR = "CHANGE_ELEMENT_FILL_COLOR"
export const CHANGE_ELEMENT_BORDER_COLOR = "CHANGE_ELEMENT_BORDER_COLOR"
export const CHANGE_ELEMENT_BORDER_WIDTH = "CHANGE_ELEMENT_BORDER_WIDTH"
